import Header from '../component/header'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/component/Providers'
import Footer from '@/component/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-green-300'>
      <body className={inter.className}>
        <Providers>
        <Header />
        <main className='m-10'>
          {children}

        </main>
        </Providers>
        <Footer />
      </body>
    </html>
  )
}
